apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdm-backend-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/yoavmanoim-prog/pdm-app
      targetRevision: develop
      path: helm/backend
      helm:
        valueFiles:
          - $values/staging/backend/values.yaml
    - repoURL: https://github.com/yoavmanoim-prog/pdm-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: pdm-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
