image:
  repository: 302954730632.dkr.ecr.us-east-1.amazonaws.com/pdm-backend
  tag: f88b301212c59e28137b29885caa4ec05355f804

replicaCount: 1

autoscaling:
  enabled: false

# staging also uses the same RDS instance (separate database schema in future)
rds:
  host: "pdm-prod-eks-postgres.ci3ceikmuv20.us-east-1.rds.amazonaws.com"

postgres:
  user: "pdm"
  password: "Yoavmanoim70"
  database: "pdm"
