image:
  repository: 302954730632.dkr.ecr.us-east-1.amazonaws.com/pdm-backend
  tag: 61b847ba0ced0b9c8fe1842785f68cebd0620ef2

replicaCount: 1

autoscaling:
  enabled: false

# staging also uses the same RDS instance (separate database schema in future)
rds:
  host: "pdm-prod-eks-postgres.ci3ceikmuv20.us-east-1.rds.amazonaws.com"

postgres:
  user: "pdm"
  password: "Yoavmanoim70"
  database: "pdm"
