image:
  repository: 302954730632.dkr.ecr.us-east-1.amazonaws.com/pdm-backend
  tag: latest

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

# point to RDS instead of the local postgres StatefulSet
rds:
  host: "pdm-prod-eks-postgres.ci3ceikmuv20.us-east-1.rds.amazonaws.com"

postgres:
  user: "pdm"
  password: "Yoavmanoim70"
  database: "pdm"
