image:
  repository: 302954730632.dkr.ecr.us-east-1.amazonaws.com/pdm-backend
  tag: 0c6b4ecbe1a29eeeb5ff40872f203021d68e86d7

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

# point to RDS instead of the local postgres StatefulSet
rds:
  host: "pdm-prod-eks-postgres.ci3ceikmuv20.us-east-1.rds.amazonaws.com"

postgres:
  user: "pdm"
  password: "Yoavmanoim70"
  database: "pdm"

vaultMode: "remote"
corsOrigins: "http://localhost:3000,http://localhost:5173,https://d3df2y18th5fg7.cloudfront.net"

ingress:
  host: pdm.52.202.248.204.nip.io
